name: unitecloud
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  nfc_manager: ^3.5.0
  ndef: ^0.3.4
  nearby_connections: ^4.3.0
  permission_handler: ^11.4.0
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
